resources:
  repositories:
    - repository: templates
      type: github
      name: dirigeants/pipelines
      endpoint: dirigeants

jobs:
  - template: lint.yml@templates

  - job: 'Test'
    dependsOn: 'Lint'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: yarn
        displayName: 'Install Dependencies'
      - script: yarn test
        displayName: 'Build / Test'
